{
 "title": "MyFirstDash",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Free Disk Space (GB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{fstype!~\"tmpfs|overlay\"}"
    }
   ]
  },
  {
   "title": "CPU Load Average (1 / 5 / 15)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "node_load1" },
    { "expr": "node_load5" },
    { "expr": "node_load15" }
   ]
  },
  {
   "title": "Free Memory (GB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes" }
   ]
  },
  {
   "title": "Title: CPU Utilization %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (\n  rate(node_cpu_seconds_total{mode=\"idle\"}[5m])\n) * 100)\n"
    }
   ]
  },
  { "type": "welcome", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 16 } },
  { "type": "gettingstarted", "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 } },
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 15, "w": 12, "x": 0, "y": 28 } },
  { "title": "Latest from the blog", "type": "news", "gridPos": { "h": 15, "w": 12, "x": 12, "y": 28 } }
 ]
}